#!/bin/bash
# Continuous Integration build script.

set -e # Exit on any error
set -x # Echo each command

# Don't run the spring application preloader on ci
export DISABLE_SPRING=1

# Install ci-specific files
find . -name '*.ci' | rename -f 's/\.ci$//'

echo '========== Install Ruby ================================================'
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
rbenv install -s
rbenv version

echo '========== Install Gems ================================================'
bundle install --no-color --local

echo '========== Prepare Database ============================================'
bin/rake db:create:all
bin/rake db:migrate
bin/rake db:test:clone

echo '========== Unit Tests =================================================='
bin/rspec spec/unit

echo '========== Component Tests ============================================='
bin/rspec spec/component

echo '========== Integration Tests ==========================================='
bin/rspec spec/integration

echo '========== Acceptance Tests ============================================'
bin/cucumber --no-color

#echo '========== Deploy To Staging ==========================================='
#bin/cap staging deploy -s branch=$GIT_COMMIT
#
#echo '========== System Tests ================================================'
#bin/rspec spec.system
