default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: living_wage_development

test: &test
  <<: *default
  database: living_wage_test

cucumber:
  <<: *test
